version: "3"

services:
  app:
    build: docker/php
    volumes:
      - ./:/app
      - ./docker/app/.bashrc:/root/.bashrc
    depends_on:
      - db
      - mailcatcher
    env_file:
      - .env
  nginx:
    image: nginx:1.12-alpine
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080

  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3360:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
      MYSQL_USER: jCh1_dbu
      MYSQL_PASSWORD: jCh1MyGod
